global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: net-report
    metrics_path: /
    scrape_interval: 10s
    scheme: http

    static_configs:
      - targets:
          - 'net-report:3200'